name: crux
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.1.6

  firebase_core: ^0.2.5+1
  cloud_firestore: ^0.7.3
  firebase_auth: ^0.5.20
  firebase_analytics: ^0.3.3
  google_sign_in: ^3.0.5

  collection: ^1.14.11

  flutter_calendar: ^0.0.8
  shared_preferences: ^0.4.3

  bloc: ^0.14.0
  flutter_bloc: ^0.14.0
  rxdart: ^0.22.0
  equatable: ^0.2.0

  spotify: ^0.1.3+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/rock-climbing-indoor-2.jpg
    - assets/images/hangboard-01.jpg
    - assets/images/campus-board-01.jpg
    - assets/images/campus-board-02.jpg
    - assets/images/campus-board-01.jpg
    - assets/images/stretching-01.jpg
    - assets/images/weightlifting-01.jpg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

#  ****IMPORTANT****
#  INDENT FAMILY TWICE FOR CUSTOM FONTS TO WORK

  fonts:
      - family: Metropolis
        fonts:
          - asset: assets/fonts/metropolis/Metropolis-Regular.otf

      - family: OpenSans
        fonts:
          - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
