enum Grip {
  SMALL_OPEN_HAND,
  MED_OPEN_HAND,
  LARGE_OPEN_HAND,
  HALF_CRIMP,
  FULL_CRIMP,
  NARROW_PINCH,
  MED_PINCH,
  WIDE_PINCH,
  SLOPER,
  JUGS,
  POCKET,
  //TODO: ANY MORE GRIPS?; FINGER CONFIGURATIONS?
}
